/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

import com.formdev.flatlaf.intellijthemes.FlatCarbonIJTheme;
import java.awt.Color;
import java.awt.Component;


/**
 *
 * @author Veronica
 */
public class ConsultaUsuario extends javax.swing.JFrame {

    /** Creates new form ConsultaUsuario */
    public ConsultaUsuario() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConsultaUsuario = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jB_NuevoUsuario = new javax.swing.JButton();
        jB_IngresarSistema = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jB_SalirConsultaUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ConsultaUsuario.setClosable(true);
        ConsultaUsuario.setTitle("Generacion de Usuario");
        ConsultaUsuario.setPreferredSize(new java.awt.Dimension(870, 680));
        ConsultaUsuario.setVisible(true);
        ConsultaUsuario.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ingreso correcto al sistema!!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 340, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Desea Ingresar al Sistema?");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 250, -1));

        jB_NuevoUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jB_NuevoUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jB_NuevoUsuario.setText("Nuevo Usuario");
        jB_NuevoUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB_NuevoUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jB_NuevoUsuario.setPreferredSize(new java.awt.Dimension(164, 33));
        jB_NuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_NuevoUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jB_NuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 150, 50));

        jB_IngresarSistema.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jB_IngresarSistema.setForeground(new java.awt.Color(0, 0, 0));
        jB_IngresarSistema.setText("Ingresar al Sistema");
        jB_IngresarSistema.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB_IngresarSistema.setPreferredSize(new java.awt.Dimension(164, 33));
        jB_IngresarSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_IngresarSistemaActionPerformed(evt);
            }
        });
        jPanel1.add(jB_IngresarSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 160, 50));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Desea Generar un Nuevo Usuario?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 315, -1));

        jB_SalirConsultaUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jB_SalirConsultaUsuario.setText("Salir");
        jB_SalirConsultaUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB_SalirConsultaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_SalirConsultaUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jB_SalirConsultaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 90, 30));

        ConsultaUsuario.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 560, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ConsultaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ConsultaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_NuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_NuevoUsuarioActionPerformed
                    
                    dispose();
                    Registro vista=new Registro();
                    vista.setVisible(true);    
    }//GEN-LAST:event_jB_NuevoUsuarioActionPerformed

    private void jB_IngresarSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_IngresarSistemaActionPerformed
    
                    dispose();
                    VacunarGUI vista=new VacunarGUI();
                    vista.setVisible(true);
    }//GEN-LAST:event_jB_IngresarSistemaActionPerformed

    private void jB_SalirConsultaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_SalirConsultaUsuarioActionPerformed
        
        dispose();
            Login log=new Login();
            log.setVisible(true);
        
    }//GEN-LAST:event_jB_SalirConsultaUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        FlatCarbonIJTheme.setup();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame ConsultaUsuario;
    private javax.swing.JButton jB_IngresarSistema;
    private javax.swing.JButton jB_NuevoUsuario;
    private javax.swing.JButton jB_SalirConsultaUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
